import Header from './Components/Header'
import './globals.css'
import { Inter } from 'next/font/google'
import { Mulish } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })
const mulish=Mulish({
  subsets: ['latin'],
  display: 'swap',
})
export const metadata = {
  title: 'Home Page',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={mulish.className}>
        <Header/>
        {children}
      </body>
    </html>
  )
}
